version: '2'
services:
  # laravel
  app:
    container_name: laravel_app
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # nginx
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 8990:80
  
  # mysql
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=LexartLabs"
      - "MYSQL_USER=phpmyadmin"
      - "MYSQL_PASSWORD=phpmyadmin"
      - "MYSQL_ROOT_PASSWORD=phpmyadmin"
    ports:
      - 8991:3306

  # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata: