version: '2'
services:
  # laravel
  app:
    container_name: app
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
    networks:
      - app-network

  # nginx
  web:
    tty: true
    container_name: nginx
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
      - ./conf/nginx:/etc/nginx/conf.d
      - ..:/var/www/html
    ports:
      - 8990:80
    links:
    - app
    depends_on:
      - app
    networks:
      - app-network
  
  # mysql
  database:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=LexartLabs"
      - "MYSQL_USER=phpmyadmin"
      - "MYSQL_PASSWORD=phpmyadmin"
      - "MYSQL_ROOT_PASSWORD=phpmyadmin"
    ports:
      - 8991:3306

  # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata:

networks:
    my-network:
        aliases:
            - app